### ISSUE TITLE
"Blevspread" reads only 14 to 15 characters when received from android laird toolkit 

### ISSUE THREAD

**Issue by savyad** [LairdCP/BL652-Applications#2]
Actually while receiving query from laird toolkit as an VSP communication,it only reads 14 characters and after 14 characters it consider it as a another msg....pls help me with it

**Comment by youssif-am-saeed** [comment]
This is not an issue because VSP is a streaming interface and by definition there isn't any packet boundary. If you'd like your application to have packet boundaries please feel free to modify the application you were using, but please ensure that you change the UUIDs when you do so as this will no longer represent Laird's custom VSP.

I hope this helps.

**Comment by savyad** [comment]
Would you please help me with it,since I am new to this I am not getting how to get it done

**Comment by mtwooburn** [comment]
What are you trying to achieve? Please describe in full before we can even comment on how to solve a problem that in our app definition (streaming interface) does not exist.

BTW: If you are expecting more than 14 characters, why are you not saving to a holding buffer and then use that buffer until you receive as many as you need?

**Comment by savyad** [comment]
What i am trying to do is like,A string from android terminal which holds config data for my application and i want that string completely not like first 14 char and then remaining ones as another string.
I am separating each string with a header which is included inside the string,using the header i will get to know what i have to do with it.
let's say
string from android is like-"radio,networkid,network_joingkey"
where,**radio** is the header and the remaining is nothing but the **config data.** 
if i want to separate a string from incoming string i will use **"Bleencodestring"** ,Say i want **radio**
in one string but it will not radio because first 14 char get overwritten by characters which comes after the 14 char(Or less). Even tough if i used a buffer to store the incoming string and append to it its no use for me(as stated above).

**Comment by mtwooburn** [comment]
Ask yourself the question "How would I design this if I had a tcp/ip connection or perhaps even a serial cable between the two?"
In both tcp/ip and serial cable, you would have the same problem !!!
What you have is a very common problem that has existed since the serial interface was invented back in the 1950's and I have solved hundreds of times in my career spanning 35 years.
The solution to your problem, given you are sending a command in string format, is to change your protocol so that EACH command and EACH response is terminated by a LineFeed (0x0A) or CarriageReturn (0x0C), \n and \r characters respectively in 'C' programming.

Then what you do is ..
All data that arrives you append and save to a holding buffer. 
Once saved in that holding buffer, you search in that holding buffer if you have your terminating character ( which you decide as which character) and if it exists, you remove that string (up to and including that terminating character) and process it.
Please ensure that when you remove that command string from your holding buffer, if the holding buffer is not empty, then you left-shift all existing data in that holding buffer and update the count.
After processing the command string, you MUST check again if there is another terminating character and then repeat that process, processing each command as you remover from that holding buffer.

I stress, what you have is not a VSP problem but how you you cache and then process the commands.

Hope this helps. There is nothing we can do because the very nature of your protocol is that you can have any length command string so if we (or you) were to modify to suit, then you still will have the same problem if you increase the length of your command

**Comment by savyad** [comment]
Thank you so much for the reply and i think it will work
