### ISSUE TITLE
Getting a compile error 

### ISSUE THREAD

**Issue by jade7272** [LairdCP/BL652-Applications#3]
Failed to compile -9; Application failed to compile
    rc = BlePhySet(hConn, PhyTx, PhyRx, 0)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compile Error: (0x0433) TOK_UNEXPECTED_TOKEN_IN_EXPR
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

File   : $autorun$.devkit.sample.app.sb
Line   : 901
Source :     rc = BlePhySet(hConn, PhyTx, PhyRx, 0)
       : ---------^

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by thedjnK** [comment]
You are seeing this compiler error because you are using an old firmware version on your module. You can either:

- Upgrade to the newest firmware, 28.7.3.0, available from the Laird BL652 website (requires an account)
- Download the applications for an older firmware, which is available from https://github.com/LairdCP/BL652-Applications/tree/B_bl652_v28_6_2_0
